global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  - /etc/prometheus/rules.yml

scrape_configs:
  - job_name: prometheus
    static_configs: [{ targets: ["localhost:9090"] }]

  - job_name: app
    metrics_path: /metrics
    static_configs:
      - targets: ["10.0.0.4:8080"]

  - job_name: nginx
    static_configs:
      - targets: ["10.0.0.4:9113"]

  - job_name: node
    static_configs:
      - targets: ["10.0.0.4:9100"]
  - job_name: minio
    metrics_path: /minio/v2/metrics/cluster
    static_configs:
      - targets: ["10.0.0.4:8080"]
alerting:
  alertmanagers:
  - static_configs:
    - targets: ["127.0.0.1:9093"]
